name: Pytest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    container: python:3.10-alpine3.17
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-poetry

      - name: Install nginx
        run: |
          apk --no-cache add nginx

      - name: Test with pytest
        working-directory: tests
        run: poetry run pytest -s --ignore=integrations
