name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    container: python:3.10-alpine3.17
    steps:
      - uses: actions/checkout@v3

      - name: Install bash and curl
        shell: sh
        run: |
          apk update
          apk add --no-cache bash curl

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Publish package
        run: poetry publish --build
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
